/*******************************************************************************
* File Name: cy_afe_configurator_settings.c
*
* Description:
* Audio Front-End Middleware configuration
* This file should not be modified. It was automatically generated by
* Audio Front-End Configurator 1.50.0.2409
*
********************************************************************************
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company) 
* or an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/


#include "cy_afe_configurator_settings.h"

afe_usb_settings_t MY_AFE_USB_SETTINGS = {
    .channel_0 = AFE_USB_SELECT_INPUT_0, // Audio Input Channel 0
    .channel_1 = AFE_USB_SELECT_INPUT_1, // Audio Input Channel 1
    .channel_2 = AFE_USB_SELECT_OUTPUT, // AEC Reference Input
    .channel_3 = AFE_USB_SELECT_AEC_REF, // AEC reference mono data
};

uint32_t AFE_FILTER_SETTINGS[] = {
0x00013200, // Audio Front End Configurator version: 1.50.0
0x00003e80, // Sampling rate
0x000000a0, // Audio frame size in number of audio samples
0x00000001, // Number of mics
0x00000000, // Number of monitored components
0x04c11db7, // CRC polynomial
0x00000004, // Number of configured components
0x00000001, // Configured component IFX_SP_ENH_IP_COMPONENT_HPF
0x00000007, // Configured component IFX_SP_ENH_IP_COMPONENT_DSNS
0x00000005, // Configured component IFX_SP_ENH_IP_COMPONENT_ANALYSIS
0x00000006, // Configured component IFX_SP_ENH_IP_COMPONENT_SYNTHESIS
0x00000002, // === HPF component parameters count
0x00000064, // HPF cutoff frequency in Hz
0x00000000, // HPF software input gain, mic #1
0x00000001, // === NS component parameters count
0x00000014, // noise suppressor gain setting
0x00000000, // === Analysis component parameters count
0x00000000, // === Synthesis component parameters count
0x44b4e23d, // Check sum calculated based on CRC polynomial
};

uint8_t AFE_MW_SETTINGS[] = {0x20, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x40, 0xa5, 0xe4, 0xf8, 0xbf, 0x9c, 0x2b, 0x72, 0x3f, 0x39, 0xfd, 0x78, 0x3f, 0x39, 0xfd, 0xf8, 0xbf, 0x39, 0xfd, 0x78, 0x3f};

