/******************************************************************************
* File Name : command_handler.h
*
* Description :
* Header for the custom voice command handler.
* Maps DeepCraft voice assistant intents to hardware actions for a
* smart room control scenario (Light, Projector, AC, Meeting, Temperature,
* Room Booking).
*******************************************************************************/

#ifndef _COMMAND_HANDLER_H_
#define _COMMAND_HANDLER_H_

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

#include <stdbool.h>
#include "voice_assistant.h"
#include "led_pwm.h"

/******************************************************************************
 * Intent Index Definitions
 * These MUST match the intent indices generated by the DeepCraft cloud tool
 * in the app_<ProjectName>.h file.
 *
 * If your DeepCraft model produces different indices, update these values
 * to match your app_<ProjectName>.h.
 *****************************************************************************/
#define INTENT_TurnOnLight          (0x0)
#define INTENT_TurnOffLight         (0x1)
#define INTENT_TurnOnProjector      (0x2)
#define INTENT_TurnOffProjector     (0x3)
#define INTENT_TurnOnAC             (0x4)
#define INTENT_TurnOffAC            (0x5)
#define INTENT_StartMeeting         (0x6)
#define INTENT_StopMeeting          (0x7)
#define INTENT_SetTemperature       (0x8)
#define INTENT_BookRoom             (0x9)

/******************************************************************************
 * Unit Index Definitions (from DeepCraft-generated app header)
 *****************************************************************************/
#define UNIT_DEGREE                 (0x0)
#define UNIT_DEGREES                (0x1)
#define UNIT_HOUR                   (0x5)
#define UNIT_HOURS                  (0x6)
#define UNIT_MINUTE                 (0x7)
#define UNIT_MINUTES                (0x8)

/******************************************************************************
 * Device State Definitions
 *****************************************************************************/
typedef enum
{
    DEVICE_OFF = 0,
    DEVICE_ON  = 1,
} device_state_t;

/******************************************************************************
 * Function Prototypes
 *****************************************************************************/

/**
 * @brief Initialize the command handler. Prints supported commands.
 */
void command_handler_init(void);

/**
 * @brief Process a detected voice command intent.
 *
 * @param intent_index  The intent index detected by the DeepCraft NLU
 * @param va_data       Pointer to voice assistant data (contains variables/units)
 */
void command_handler_process(int intent_index, va_data_t *va_data);

/**
 * @brief Process a detected command string (model-name/intent-order agnostic).
 *
 * This is the preferred entry-point if you are not sure the final DeepCraft
 * model name/intent indices yet. It normalizes the command text and maps it
 * to the smart-room actions (light/projector/AC/meeting/temp/booking).
 *
 * @param command_text  Recognized command text (may include wake word prefix)
 * @param va_data       Optional VA data; used as a fallback for numeric values
 *
 * @return true if a supported command was recognized and executed
 */
bool command_handler_process_text(const char *command_text, const va_data_t *va_data);

/**
 * @brief Print the list of supported commands to UART.
 */
void command_handler_print_commands(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus */

#endif /* _COMMAND_HANDLER_H_ */

/* [] END OF FILE */
