/******************************************************************************
* File Name : command_handler.h
*
* Description :
* Header for the custom voice command handler.
* Maps DeepCraft voice assistant intents to hardware actions for a
* smart room control scenario (Light, Projector, AC, Meeting, Temperature,
* Room Booking).
*******************************************************************************/

#ifndef _COMMAND_HANDLER_H_
#define _COMMAND_HANDLER_H_

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

#include <stdbool.h>
#include "voice_assistant.h"
#include "led_pwm.h"

/* Include the DeepCraft-generated app header so intent and unit indices
 * stay in sync automatically when the real model is dropped in.
 * This header is generated by the DEEPCRAFT cloud tool and placed in
 * va_models/<ProjectName>/app_<ProjectName>.h                          */
#include "app_Smart_Room_Control.h"

/******************************************************************************
 * Intent Index Definitions — derived from the generated app header.
 * These update automatically when you replace the DeepCraft model files.
 *****************************************************************************/
#define INTENT_TurnOnLight          SMART_ROOM_CONTROL_INTENT_TurnOnLight
#define INTENT_TurnOffLight         SMART_ROOM_CONTROL_INTENT_TurnOffLight
#define INTENT_TurnOnProjector      SMART_ROOM_CONTROL_INTENT_TurnOnProjector
#define INTENT_TurnOffProjector     SMART_ROOM_CONTROL_INTENT_TurnOffProjector
#define INTENT_TurnOnAC             SMART_ROOM_CONTROL_INTENT_TurnOnAC
#define INTENT_TurnOffAC            SMART_ROOM_CONTROL_INTENT_TurnOffAC
#define INTENT_StartMeeting         SMART_ROOM_CONTROL_INTENT_StartMeeting
#define INTENT_StopMeeting          SMART_ROOM_CONTROL_INTENT_StopMeeting
#define INTENT_SetTemperature       SMART_ROOM_CONTROL_INTENT_SetTemperature
#define INTENT_BookRoom             SMART_ROOM_CONTROL_INTENT_BookRoom

/******************************************************************************
 * Unit Index Definitions — derived from the generated app header.
 *****************************************************************************/
#define UNIT_DEGREE                 SMART_ROOM_CONTROL_UNIT_degree
#define UNIT_DEGREES                SMART_ROOM_CONTROL_UNIT_degrees
#define UNIT_HOUR                   SMART_ROOM_CONTROL_UNIT_hour
#define UNIT_HOURS                  SMART_ROOM_CONTROL_UNIT_hours
#define UNIT_MINUTE                 SMART_ROOM_CONTROL_UNIT_minute
#define UNIT_MINUTES                SMART_ROOM_CONTROL_UNIT_minutes

/******************************************************************************
 * Device State Definitions
 *****************************************************************************/
typedef enum
{
    DEVICE_OFF = 0,
    DEVICE_ON  = 1,
} device_state_t;

/******************************************************************************
 * Function Prototypes
 *****************************************************************************/

/**
 * @brief Initialize the command handler. Prints supported commands.
 */
void command_handler_init(void);

/**
 * @brief Process a detected voice command intent.
 *
 * @param intent_index  The intent index detected by the DeepCraft NLU
 * @param va_data       Pointer to voice assistant data (contains variables/units)
 */
void command_handler_process(int intent_index, va_data_t *va_data);

/**
 * @brief Process a detected command string (model-name/intent-order agnostic).
 *
 * This is the preferred entry-point if you are not sure the final DeepCraft
 * model name/intent indices yet. It normalizes the command text and maps it
 * to the smart-room actions (light/projector/AC/meeting/temp/booking).
 *
 * @param command_text  Recognized command text (may include wake word prefix)
 * @param va_data       Optional VA data; used as a fallback for numeric values
 *
 * @return true if a supported command was recognized and executed
 */
bool command_handler_process_text(const char *command_text, const va_data_t *va_data);

/**
 * @brief Print the list of supported commands to UART.
 */
void command_handler_print_commands(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus */

#endif /* _COMMAND_HANDLER_H_ */

/* [] END OF FILE */
